import type { BaseRow, TableMap, TableName } from "./types";

export type DataTable = Exclude<TableName, "activity_logs">;
export type RowValues<T extends DataTable> = Omit<TableMap[T], keyof BaseRow>;

export const DEFAULTS: { [K in DataTable]: RowValues<K> } = {
  tasks: {
    title: "",
    category: null,
    due_date: null,
    status: "todo",
    priority: "normal",
    assignee: "both",
    memo: null,
    vendor_id: null,
    budget_item_id: null,
    is_favorite: false,
    completed_at: null,
    sort_order: 0,
  },
  budget_categories: { name: "", icon: null, sort_order: 0, planned_amount: 0 },
  budget_items: {
    category_id: null,
    name: "",
    estimated_amount: 0,
    actual_amount: 0,
    vendor_name: null,
    vendor_id: null,
    memo: null,
    is_favorite: false,
    sort_order: 0,
  },
  payments: {
    budget_item_id: "",
    title: "결제",
    amount: 0,
    due_date: null,
    paid: false,
    paid_at: null,
    memo: null,
  },
  vendors: {
    category: "other",
    name: "",
    contact_name: null,
    phone: null,
    url: null,
    reserved_date: null,
    visit_date: null,
    deposit: 0,
    balance: 0,
    total_amount: 0,
    payment_status: "unpaid",
    status: "candidate",
    memo: null,
    is_favorite: false,
    details: {},
  },
  venues: {
    name: "",
    address: null,
    event_date: null,
    event_time: null,
    is_contracted: false,
    deposit: 0,
    balance: 0,
    hall_fee: 0,
    meal_cost: 0,
    guaranteed_guests: 0,
    expected_guests: 0,
    parking: null,
    transport: null,
    notes: null,
    contact_name: null,
    phone: null,
    url: null,
    memo: null,
    is_favorite: false,
  },
  honeymoon: {
    country: null,
    city: null,
    depart_date: null,
    return_date: null,
    flight_info: null,
    flight_booked: false,
    flight_booking_no: null,
    hotel_name: null,
    hotel_booked: false,
    hotel_booking_no: null,
    cost: 0,
    memo: null,
  },
  honeymoon_items: { kind: "checklist", title: "", date: null, time: null, done: false, memo: null, sort_order: 0 },
  music_items: {
    slot: "other",
    title: "",
    artist: null,
    url: null,
    section: null,
    is_confirmed: false,
    memo: null,
    sort_order: 0,
  },
  outfit_items: {
    kind: "신랑 예복",
    vendor_name: null,
    reserve_date: null,
    fitting_date: null,
    pickup_date: null,
    cost: 0,
    is_paid: false,
    memo: null,
    is_favorite: false,
  },
  guests: {
    name: "",
    side: "groom",
    relation: null,
    rsvp: "maybe",
    companions: 0,
    meal: "unknown",
    contacted: false,
    invitation_sent: false,
    invitation_method: null,
    memo: null,
  },
  invitation_meetings: {
    title: "",
    target: null,
    date: null,
    time: null,
    place: null,
    attendees: null,
    attendee_count: 0,
    estimated_cost: 0,
    actual_cost: 0,
    status: "planned",
    memo: null,
    event_id: null,
  },
  gifts: {
    recipient: "",
    relation: null,
    item: null,
    estimated_cost: 0,
    actual_cost: 0,
    is_purchased: false,
    is_delivered: false,
    delivered_at: null,
    memo: null,
  },
  events: {
    title: "",
    type: "other",
    date: "",
    start_time: null,
    end_time: null,
    location: null,
    memo: null,
    source_type: null,
    source_id: null,
    is_done: false,
  },
  memos: { content: "", converted_to: null },
  attachments: { entity_type: "", entity_id: "", storage_path: "", file_name: "", mime_type: null, size: 0 },
};
